# Generated by Django 4.0.3 on 2022-04-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_image_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.ImageField(upload_to='uploads/', verbose_name='image_path'),
        ),
    ]
