# Generated by Django 4.0.3 on 2022-04-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_image_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('paid', 'paid'), ('shipped', 'shipped'), ('finished', 'finished')], default='ordered', max_length=50, verbose_name='status'),
        ),
    ]
