# Generated by Django 4.0.3 on 2022-05-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_slug_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='url-slug', editable=False, max_length=255, verbose_name='slug'),
        ),
    ]
