# Generated by Django 4.0.3 on 2022-05-10 21:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='transaction id'),
        ),
    ]
