# Generated by Django 3.2.13 on 2022-06-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_newsletter_alter_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, verbose_name='quantity'),
        ),
    ]
