# Generated by Django 3.2.13 on 2022-06-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_order_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='', max_length=30, verbose_name='order_number'),
        ),
    ]
