# Generated by Django 3.2.13 on 2022-06-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='order_number'),
        ),
    ]
