# Generated by Django 3.2.13 on 2022-07-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'CartProduct', 'verbose_name_plural': 'CartProducts'},
        ),
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name': 'CategoryProduct', 'verbose_name_plural': 'CategoryProducts'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletters'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'OrderProduct', 'verbose_name_plural': 'OrderProducts'},
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
    ]
