# Generated by Django 3.2.13 on 2022-11-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20221013_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.ImageField(upload_to='uploads/', verbose_name='image_path'),
        ),
    ]
